baseURL = "http://localhost:1313/"
title = "Puppet Theme"

copyright = ""
paginate = 3
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = false
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

theme = "puppet"
themesDir = "../.."

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[params]
author = "Puppet"
description = "A simple and clean theme for Hugo"
keywords = "blog,developer,personal"
img_home = "/img/home-bg.jpg"
img_404 = "/img/404-bg.jpg"

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]


[params.sidebar]
enable = true
avatar = "/img/home-bg.jpg"
bio = "a personal website"

[params.social]
rss_enable = true
twitter = "johndoe"
facebook = "johndoe"
zhihu = "johndoe"
weibo = "johndoe"
github = "johndoe"
linkedin = "johndoe"

[[params.friends]]
name = "John Doe"
url = "https://gohugo.io"

[[params.friends]]
name = "John Doe"
url = "https://gohugo.io"

# See https://giscus.app/
[params.giscus]
enable = true
repo = "roninro/hugo-theme-puppet"
repo_id = "R_kgDOHuvyhw"
category = "General"
category_id = "DIC_kwDOHuvyh84CQjDo"
input_position = "top"
theme = "light_tritanopia"
lang = "en"

